# Generated by Django 5.0.4 on 2024-05-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersignin', '0003_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttranslationpart',
            name='project_name',
            field=models.TextField(default='null'),
        ),
    ]
