# Generated by Django 5.0.4 on 2024-05-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termbanklist',
            name='number_of_terms',
            field=models.IntegerField(default=0),
        ),
    ]
