# Generated by Django 5.0.4 on 2024-06-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialdata', '0002_alter_termbanklist_number_of_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termbankitem',
            name='term_bank_name',
        ),
    ]
