# Generated by Django 5.0.4 on 2024-05-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryBankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_bank_name', models.CharField(max_length=32)),
                ('memory_item_id', models.IntegerField()),
                ('original_language_text', models.CharField(max_length=32)),
                ('target_language_text', models.CharField(max_length=32)),
                ('import_time', models.DateTimeField(auto_now_add=True)),
                ('number_of_calls', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MemoryBankList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_bank_name', models.CharField(max_length=32)),
                ('original_language', models.CharField(max_length=32)),
                ('target_language', models.CharField(max_length=32)),
                ('number_of_memory_items', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TermBankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_bank_name', models.CharField(max_length=32)),
                ('term_item_id', models.IntegerField()),
                ('original_language_text', models.CharField(max_length=32)),
                ('target_language_text', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TermBankList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_bank_name', models.CharField(max_length=32)),
                ('original_language', models.CharField(max_length=32)),
                ('target_language', models.CharField(max_length=32)),
                ('number_of_term_items', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('project_name', models.CharField(max_length=32)),
                ('import_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
