# Generated by Django 5.0.4 on 2024-05-30 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorydata', '0001_initial'),
        ('usersignin', '0003_remove_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryBankList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_language', models.CharField(max_length=255)),
                ('target_language', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersignin.user')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('target_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersignin.user')),
                ('memory_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorydata.memorybanklist')),
            ],
        ),
        migrations.DeleteModel(
            name='Memorydatatable',
        ),
    ]
