# Generated by Django 5.0.4 on 2024-06-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorydata', '0002_memorybanklist_memorybankdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorybankdetail',
            name='called_count',
        ),
        migrations.RemoveField(
            model_name='memorybankdetail',
            name='created_at',
        ),
    ]
