# Generated by Django 5.0.4 on 2024-06-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorydata', '0003_remove_memorybankdetail_called_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorybanklist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='memorybanklist',
            name='updated_at',
        ),
    ]
